// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp9VIRy2tmkUHNCuJEJUZWP98vv-xr2bI',
    appId: '1:470415610035:web:2b9b7bee0b74ec11a760c6',
    messagingSenderId: '470415610035',
    projectId: 'shark-stage-4e60d',
    authDomain: 'shark-stage-4e60d.firebaseapp.com',
    storageBucket: 'shark-stage-4e60d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9rwq0MlyvuaepNvEuDzjKbGmE5ZvxDp0',
    appId: '1:470415610035:android:0e792d2ed47d9622a760c6',
    messagingSenderId: '470415610035',
    projectId: 'shark-stage-4e60d',
    storageBucket: 'shark-stage-4e60d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDZcB8SsZ4_d03v8lCjWJ85vOHzpCWYbw',
    appId: '1:470415610035:ios:601250906931afa6a760c6',
    messagingSenderId: '470415610035',
    projectId: 'shark-stage-4e60d',
    storageBucket: 'shark-stage-4e60d.firebasestorage.app',
    iosBundleId: 'com.example.finialProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDZcB8SsZ4_d03v8lCjWJ85vOHzpCWYbw',
    appId: '1:470415610035:ios:601250906931afa6a760c6',
    messagingSenderId: '470415610035',
    projectId: 'shark-stage-4e60d',
    storageBucket: 'shark-stage-4e60d.firebasestorage.app',
    iosBundleId: 'com.example.finialProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp9VIRy2tmkUHNCuJEJUZWP98vv-xr2bI',
    appId: '1:470415610035:web:0963e4180d2c82c9a760c6',
    messagingSenderId: '470415610035',
    projectId: 'shark-stage-4e60d',
    authDomain: 'shark-stage-4e60d.firebaseapp.com',
    storageBucket: 'shark-stage-4e60d.firebasestorage.app',
  );

}